#!/usr/bin/env bash
# =====================================================================
# setup-labels.sh — idempotent GitHub label setup (universal core + packs)
#
# WHAT IT DOES
#   Creates a consistent label taxonomy on a repo via the gh CLI. Re-runnable:
#   `--force` updates an existing label in place instead of failing, so this is
#   safe to run as many times as you like. Additive by default — the only
#   destructive part (prune) is commented out and must be opted into deliberately.
#
# USAGE
#   chmod +x setup-labels.sh
#   ./setup-labels.sh                 # applies to the current repo
#   ./setup-labels.sh owner/repo      # applies to a specific repo
#
# REQUIRES
#   gh (authenticated — check with `gh auth status`)
#
# HOW AN AGENT SHOULD USE THIS
#   1) Run the audit (read-only) to see existing labels.
#   2) Keep the UNIVERSAL CORE as-is.
#   3) Uncomment ONLY the packs this repo needs (DE / ML / LLM-RAG / Agentic /
#      domain). Packs mirror the issue/PR/task-brief/checklist vocabulary.
#   4) Run the script. Then run the VERIFY step and report the label list.
#   Do NOT enable the PRUNE section without explicit human approval.
# =====================================================================

set -euo pipefail

REPO="${1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
echo "▶ Target repo: $REPO"

mklabel() {  # $1=name  $2=color(hex, no #)  $3=description
  gh label create "$1" --color "$2" --description "$3" --force --repo "$REPO"
}

# Regenerate the agent-facing label reference from the LIVE repo (source of truth),
# so issue/PR-building agents always cite labels that actually exist on this repo.
generate_labels_doc() {
  local root out
  root="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
  out="$root/.github/docs/project_labels.md"
  mkdir -p "$root/.github/docs"
  {
    echo "<!-- AUTO-GENERATED by scripts/setup-labels.sh — do not edit by hand."
    echo "     Re-run the script to refresh after changing labels. -->"
    echo "# Project Labels — $REPO"
    echo
    echo "_Generated $(date -u +%Y-%m-%d) from the live repo. This is the label reference"
    echo "for agents building issues and PRs — apply only labels listed here._"
    echo
    echo "## How to apply (agent rules)"
    echo "- Exactly **one** \`type:\` label per issue/PR."
    echo "- Exactly **one** \`priority:\` label (P0/P1/P2)."
    echo "- **One** \`status:\` label at a time (issues)."
    echo "- Any number of \`area:\` labels that apply."
    echo "- Add \`safety:\` labels whenever the change touches a human-gate or kill-switch path."
    echo "- Use \`engine:\`/\`domain:\` labels only if present below."
    echo
    gh label list --repo "$REPO" --json name,description --limit 200 \
      | python3 -c "$(cat <<'PY'
import sys, json
labels = json.load(sys.stdin)
groups = {}
for lab in labels:
    name = lab["name"]
    prefix = name.split(":", 1)[0].strip() if ":" in name else "other"
    groups.setdefault(prefix, []).append(lab)
order = ["type", "priority", "status", "area", "safety", "engine", "domain", "other"]
ordered = [g for g in order if g in groups] + sorted(g for g in groups if g not in order)
for g in ordered:
    print(f"### {g}\n")
    print("| Label | Description |")
    print("|-------|-------------|")
    for lab in sorted(groups[g], key=lambda x: x["name"]):
        desc = (lab.get("description") or "").replace("|", "\\|")
        print(f"| `{lab['name']}` | {desc} |")
    print()
PY
)"
  } > "$out"
  echo "✓ Wrote $out"
}

# ── AUDIT (read-only) — see what's there before changing anything ─────
echo "▶ Existing labels:"
gh label list --repo "$REPO" || true

# =====================================================================
# UNIVERSAL CORE  (every repo gets these — keep consistent everywhere)
# =====================================================================

# type: — blue family
mklabel "type: feature"  "0075CA" "New functionality"
mklabel "type: bug"      "D73A4A" "Defect or incorrect behavior"
mklabel "type: docs"     "0052CC" "Documentation updates"
mklabel "type: test"     "5319E7" "Tests / coverage"
mklabel "type: refactor" "006B75" "Refactor without behavior change"
mklabel "type: chore"    "BFD4F2" "Tooling / deps / maintenance"

# priority: — red→amber gradient
mklabel "priority: P0" "B60205" "Urgent / blocking"
mklabel "priority: P1" "D93F0B" "High priority"
mklabel "priority: P2" "FBCA04" "Normal priority"

# status: — green family (apply one at a time)
mklabel "status: in progress"  "0E8A16" "Actively being worked"
mklabel "status: needs review" "C2E0C6" "Ready for review"
mklabel "status: blocked"      "006B29" "Waiting on a dependency"

# area: — neutral family (generic areas useful in any repo)
mklabel "area: config"    "C5DEF5" "Config / schema mappings"
mklabel "area: notebooks" "FEF2C0" "Notebooks / walkthroughs"
mklabel "area: data-viz"  "D2DAE1" "Plots / KPIs / dashboards"
mklabel "area: ci"        "D4C5F9" "CI/CD / GitHub Actions"

# =====================================================================
# PROJECT PACKS  — uncomment the ones a given repo needs
# (Same vocabulary as your issue/PR/task-brief/checklist packs.)
# =====================================================================

# ── DE pack ──────────────────────────────────────────────────────────
# mklabel "area: pipeline"     "1D76DB" "Ingestion / ETL / orchestration"
# mklabel "area: schema"       "0052CC" "Canonical schema / contracts"
# mklabel "area: data-quality" "0E8A16" "Validation / nulls / dedupe / idempotence"
# mklabel "area: export"       "C5DEF5" "Output / correction-template export"

# ── ML pack ──────────────────────────────────────────────────────────
# mklabel "area: model"      "5319E7" "Model code / training"
# mklabel "area: eval"       "8256D0" "Metrics / thresholds / regression gates"
# mklabel "area: experiment" "A371F7" "Experiment tracking / runs"
# mklabel "area: dataset"    "D4C5F9" "Datasets / splits / versioning"

# ── LLM / RAG pack ───────────────────────────────────────────────────
# mklabel "area: retrieval"  "006B75" "Chunking / embeddings / vector-graph store"
# mklabel "area: prompts"    "0075CA" "Prompt versioning / templates"
# mklabel "area: eval"       "8256D0" "DeepEval / RAGAS / GEval gates"
# mklabel "area: cost"       "FBCA04" "Token / latency / spend budget"
# mklabel "area: guardrails" "D73A4A" "PII / injection / output validation"

# ── Agentic pack (+ safety) ──────────────────────────────────────────
# mklabel "area: agent-loop"    "006B75" "Loop / planning / tool orchestration"
# mklabel "area: tools"         "C5DEF5" "Tool integrations / MCP"
# mklabel "area: observability" "D4C5F9" "Tracing / audit logs"
# mklabel "safety: human-gate"  "B60205" "Requires human sign-off before action"
# mklabel "safety: kill-switch" "B60205" "Touches the kill-switch / live path"

# ── Domain pack — EXAMPLE: 1099 reconciliation pipeline (your original) ─
# mklabel "engine: A-reconcile"    "0366D6" "Relius <-> Matrix reconciliation engine"
# mklabel "engine: B-age"          "0366D6" "Age-based tax code engine"
# mklabel "engine: C-roth-taxable" "0366D6" "Roth taxable + basis engine"
# mklabel "engine: D-ira-rollover" "0366D6" "IRA rollover engine"

# =====================================================================
# OPTIONAL PRUNE  (DESTRUCTIVE — leave commented unless approved)
# Removes GitHub's noisy default labels that don't fit this workflow.
# Deleting a label removes it from any issues/PRs it was on.
# =====================================================================
# for l in "duplicate" "invalid" "question" "wontfix" \
#          "good first issue" "help wanted" "enhancement" "documentation" "bug"; do
#   gh label delete "$l" --repo "$REPO" --yes 2>/dev/null || true
# done

# ── VERIFY ───────────────────────────────────────────────────────────
echo "✓ Labels applied. Current labels:"
gh label list --repo "$REPO"

# ── GENERATE AGENT-FACING REFERENCE DOC ──────────────────────────────
# Writes .github/docs/project_labels.md from the live repo. Commit this file so
# the issue/PR-building agent references the correct labels for THIS repo.
generate_labels_doc