""" """

# =============================================================================
# IMPORTS
# =============================================================================

from __future__ import annotations

from pathlib import Path
from typing import Final

# =============================================================================
# MODULE CONFIGURATION
# =============================================================================
# =====================================================
# Constants
# =====================================================

ROOT: Final[Path] = Path(__file__).resolve().parent.parent
SOURCE_DIR: Final[Path] = ROOT / ".cursor" / "rules"
OUTPUT_DIR: Final[Path] = ROOT / ".claude" / "rules"

# Rule files that are deliberately NOT mirrored into Claude Code.
#
# learning-mode: consumed by the `learn` output style, which is generated by
# build_claude_agents.py. Mirroring it here would load it into every session as well.
EXCLUDE: frozenset[str] = frozenset({"learning-mode"})

BANNER: str = (
    "<!-- GENERATED FILE — DO NOT EDIT.\n"
    "     Body:    .cursor/rules/{name}.mdc\n"
    "     Scoping: the `globs:` field in that file\n"
    "     Rebuild: make claude-rules\n"
    "\n"
    "     `.claude/rules/` does not expand @path imports (ADR-0008), so this file\n"
    "     carries a full copy of the rule body rather than a pointer to it.\n"
    "-->\n"
)


class RuleError(Exception):
    """A source rule file cannot be rendered."""


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _unquote(value: str) -> str:
    """Strip one layer of matching single or double quotes."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value
